language: node_js
cache:
directories:
- node_modules
notifications:
email: false
branches:
except:
env:
  global:
  - secure: esvvZQjX1uwAUBdDao5V8dzMFah9NEL3uSb9fbiKcQunegTBZEU3RoAuHywYshghskZ4MXKhe+6vyjAJvVrV5pcD2bdEHQCOEySfoDs+doLwKjH9bPZOefQ7WMOZF9xHAJ/OzhFyQECwH2Z9t3pHAvApraGszUyzSSU+OS0FQKqvdvG65E0mMTc1E60l6lbH12hHs8+cSrM6BUuiesUD8wwWFMABSZFTdkQV7QPlRKy7fSban/PelBDpvqnEQj1j8qCwTnQyakGl0J6BhmlaCtEjaRcSWK80D8CmhoPaFIjz7gR9gxFOpPaVq5jjWtjIIN++N4gsnpQNASt0l9WZTJHl2QOvCdOh2KDa0WSWj81Ic7S0+70+Qfawi4M2wMjiH+pS10dQj9KE/FZoHUGLu4HWvviLkLKX5DfCrQm+ehQPGP/HWslXlFpKrbFGOshn6xhUFZBa+jp1kcZjYDpCACVnNa6GJfr5hF4JlD9/00yafaGovtV56BjSHuj5Zn4KJidZD8xIP7Wg+Vlvhvf08UB+HiBEX+lMJaZRAcFZMg3rPNe9UfdHffk+i7LCWKUdFW4lbd8vn3yj2zzlsfKaOihIS+R+kvuWOX1nHndmC94GF1ZWo28DY55Dqud8AdtAwYn+iQNOfkgA2RSbi8gtarTC5Ehx6GbBKkp2tavVXIc=
  - secure: qAbKHqkySDVvSs/eNVOiUK7c5lIuaPWOtr5y0rvGW8VwlocKdFpiM9d/mZP0ox6CmwwP2RzePSoQ/EKYVX4pP/qlmA09b8E2U59+kmfeN1VVBlQ8Bc7isfvSLIOQex6XYNETiMqbPjV4r9VFMQ4plE6X0cr6PO+fgvuiO11Toqd9iIDucMqJKdtG/ERhuNt1Rp0pPUJee8RXtrxk54Dv/kVwEbNzc8n6BIpUwhbNKlbsKtgMtgc5vcjD0/rwFpaFTVmVuyfjasMngKbgmYIpRQEXo2tmF7zwQpdI+EFOIcffCv5n34tTYPO3dPQ3ju3GM84pzFkpG6ERz2rqTpK/UjTtt/t09l1smZQ1G/Fl6j/LvFPHzMJv+03RB4ItnuV1VnNz92Fqec4P6WzOiWIaWRvbssXjW4EU48ss0NZFkWanioeebV0F3IKjM30Zz+dmzYXnUk+t/+felWHfWPxMfA3ixbv5kk/tcflrv9+OCYVsn94U8vX6cF3T1HpYoF+ldndny5uswywG+ga0+u0oCI7B45ifcgnn+/l63b2fHvs11uQTEfBNXupEL7tM6gQDaYyScN2Y2YLX44cOobEJxGp74RBPw0DtPDJse4BYS0Ge7rEn/q2bHfGruoAMl/gbUnVYeIsx4xoMsX2GCPupkw/tXaBbZMcAkZdcvKJx5oE=
